# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libnsdfile and libsox
      run: |
        sudo apt update
        sudo apt install libsndfile1-dev libsndfile1 ffmpeg
        sudo apt install --fix-missing sox libsox-dev libsox-fmt-all
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir numpy
        pip install --no-cache-dir '.[tests]'
        pip install smart_open[http]  # for URL audio downloading test
    - name: Install Python dependencies
      run: |
        lhotse install-sph2pipe  # Handle sphere files.
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --exclude deps/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --exclude deps/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest and coverage
      run: |
        coverage run -m pytest test
    - name: Generate and upload the coverage report
      run: |
        coverage xml
        bash <(curl -s https://codecov.io/bash)
